# Server
server:
  error:
    include-binding-errors: always
    include-message: always
    include-exception: true
  shutdown: graceful
  port: 8080

spring:
  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/Converter
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # Liquibase
  liquibase:
    change-log: classpath:liquibase/db.changelog_master.yaml
    url: jdbc:postgresql://localhost:5432/Converter
    user: postgres
    password: admin