
spring:
  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/Converter
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  graphql:
    graphiql:
      enabled: true
#    cors:
#      allowed-origins: *
#    schema:
#      printer:
#        enabled: true

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: false

  # Liquibase
  liquibase:
    change-log: classpath:liquibase/db.changelog_master.yaml
    url: jdbc:postgresql://localhost:5432/Converter
    user: postgres
    password: admin